### ISSUE TITLE
Struct code typo?

### ISSUE THREAD

**Issue by aCupOfKoffi** [Neo-Zhixing/vkdoc.net#2]
On a [VkPipelineShaderStageCreateInfo page](https://vkdoc.net/man/VkPipelineShaderStageCreateInfo) pName member is repeated.
![image](https://github.com/Neo-Zhixing/vkdoc.net/assets/85884178/64e2edba-e295-4110-a9fe-2e8eea238ee8)

**Comment by PixelDust22** [comment]
Looks strange, I'll look into it.

**Comment by PixelDust22** [comment]
Fixed. Thanks for reporting this!

**Comment by aCupOfKoffi** [comment]
Yep, no problem
