### ISSUE TITLE
Another one struct code typo?

### ISSUE THREAD

**Issue by aCupOfKoffi** [Neo-Zhixing/vkdoc.net#3]
Repeated struct member. [This page.](https://vkdoc.net/man/vkCreateSwapchainKHR)
![image](https://github.com/Neo-Zhixing/vkdoc.net/assets/85884178/3ad81193-fe53-498d-bdab-ab562d19f078)

**Comment by PixelDust22** [comment]
Fixed. Thanks for reporting this!
