### ISSUE TITLE
Function args are unreadable with JS disabled

### ISSUE THREAD

**Issue by mikejsavage** [Neo-Zhixing/vkdoc.net#6]
e.g. https://vkdoc.net/man/vkCmdPushDescriptorSetWithTemplateKHR

![image](https://github.com/Neo-Zhixing/vkdoc.net/assets/579299/6eed85b1-f375-4faf-9e80-fa5884f0e8da)

Fair enough if you don't care about fixing this

**Comment by PixelDust22** [comment]
This is definitively something we can fix!

**Comment by PixelDust22** [comment]
Fixed. Thanks for reporting this!
