### ISSUE TITLE
[Feature Request] Have a way to paste text in search bar without having to delete previous search

### ISSUE THREAD

**Issue by St0wy** [Neo-Zhixing/vkdoc.net#7]
Thanks a lot for the amazing tool, it is very helpful ! There is just one thing that I think could help a lot :

When being on a page after a search, the search bar is empty. This makes me think that I should be able to click on the search bar and directly paste some text, but the previous search remains in the search popup.

I think it would make sense if the search bar has the previous search in it in that case, and also I think it would be convenient to have the previous search be selected when we open the search bar so that we are able to directly paste the new search.

**Comment by PixelDust22** [comment]
Yeah this is most likely a bug. I’ll get it fixed asap

**Comment by PixelDust22** [comment]
I have made it so that the search bar clears the text upon opening a search result, so hopefully this change will address your concern. Thanks for your suggestion!
