### ISSUE TITLE
Example code not visible in android

### ISSUE THREAD

**Issue by kryptoid256** [Neo-Zhixing/vkdoc.net#8]

**Comment by PixelDust22** [comment]
I do not have any android devices to test this - can you upload a screen shot to demonstrate?

**Comment by kryptoid256** [comment]
![Screenshot_2024-07-01-02-10-33-62_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Neo-Zhixing/vkdoc.net/assets/86027746/60194874-9b80-456b-be90-f713670dac2e)

This is how it looked on Chrome.

![Screenshot_2024-07-01-02-14-07-55_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Neo-Zhixing/vkdoc.net/assets/86027746/6308d7ad-482d-4784-bc7f-83b4750a45c2)

And this is how it looked on Chrome with Desktop Site view on.

**Comment by PixelDust22** [comment]
Ok thank you. This seems like a data issue. Will investigate.

**Comment by kryptoid256** [comment]
By the way I tested on Windows Chrome and found the same issue
![Capture](https://github.com/Neo-Zhixing/vkdoc.net/assets/86027746/79098977-937c-4756-8953-35429cc7dbcf)

**Comment by PixelDust22** [comment]
Fixed. Thanks for reporting this!
