### ISSUE TITLE
Wrong definition for VkAccelerationStructureGeometryDataKHR

### ISSUE THREAD

**Issue by Zieng** [Neo-Zhixing/vkdoc.net#9]
<img width="732" alt="image" src="https://github.com/user-attachments/assets/5313f447-a422-41e5-8f63-e5e2888a9f78">

In the vkdoc.net, this is defined as a struct: https://vkdoc.net/man/VkAccelerationStructureGeometryDataKHR
Instead it should be an union: https://docs.vulkan.org/spec/latest/chapters/accelstructures.html#VkAccelerationStructureGeometryDataKHR

**Comment by PixelDust22** [comment]
Thanks for reporting this! Fix incoming

**Comment by PixelDust22** [comment]
Fixed. Thanks again!
